config/routes.rb
Rails.application.routes.draw do
  resources :charges, only: [:new, :create]

  devise_for :users

  resources :downgrade do
    collection do
      get :downgrade
    end
  end

  resources :users, only: [:show, :update]

  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  get 'welcome/index'

  root 'welcome#index'
end

app/models/amount.rb
class Amount
  def self.default
    10_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis

  before_save { self.role ||= :standard }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

  def collaborator_for(user)
    collaborators.where(user: user).first
  end

  def public?
    !private?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit

  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:alert] = "You must be an admin to do that."
    redirect_to wikis_path
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.premium!

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to edit_user_registration_path

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.email}",
     amount: Amount.default
   }
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def index
    @users = User.all
  end

  def create
    # Collaborator.create!(collaborator_params)
    # redirect_to edit_wiki_path(@wiki)
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])
    if @collaborator.save
      # flash good
    else
      # flash bad
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      # flash good
    else
      #flash bad
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def downgrade
    current_user.standard!
    current_user.wikis.update_all(private: false)

    flash[:notice] = "Your account has been successfully downgraded."
    redirect_to edit_user_registration_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborators = @wiki.users
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = current_user.wikis.new(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])

    authorize @wiki

    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new()
    extensions = {
      hard_wrap: true, filter_html: true
    }

    Redcarpet::Markdown.new(renderer).render(content).html_safe
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def can_make_private_for(wiki)
    current_user.admin? || (current_user.premium? && (wiki.new_record? || wiki.user == current_user))
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>Manage Collaborators for <%= @wiki.title %></h1>

<table class="table table-striped">
  <thead>
    <th>Email</th>
    <th></th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td>
          <% if @wiki.users.include? user %>
            <%= link_to "Remove", wiki_collaborator_path(@wiki, @wiki.collaborator_for(user)), method: :delete, class: "btn btn-danger" %>
          <% else %>
            <%= link_to "Add", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "Back to #{@wiki.title}", @wiki %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <% if user_signed_in? %>
      <div class="signed-in">
        Signed in as: <strong><%= current_user.email %></strong>
      </div>
    <% end %>
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>

      <% if user_signed_in? %>
        <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        <li><%= link_to 'Wikis', wikis_path, :class => 'navbar-link' %></li>
      <% else %>
        <li><%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link'  %></li>
      <% end %>
    </ul>

    <div class="flash">
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>

    <%= yield %>

  </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Blocipedia</h1>
<p>an application that allows users to create public and private Markdown-based wikis.</p>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="check-box">
    <% if can_make_private_for(@wiki) %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>
<div>
  <%= link_to "Manage Collaborators", wiki_collaborators_path(@wiki), class: "link" %>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
          </h4>
        </div>
      </div>
    <% end %>
    </div>
    <div class="col-md-4">
      <%= link_to "New", new_wiki_path(@new), class: 'btn btn-success' %>
    </div>
  </div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
<div class="row">
  <div class="col-md-8">
    <%= render "form" %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
<div class="row">
  <div class="col-md-8">
    <%= markdown @wiki.body %>
    <% if @wiki.private? %>
      <p><strong>This wiki is private</strong></p>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
  </div>
</div>

<h2>Collaborators</h2>
<% @collaborators.each do |collaborator| %>
  <div class="row">
    <div class="col-md-8">
      <%= collaborator.email %>
    </div>
  </div>
<% end %>